{
  "formatVersion": "1.1",
  "component": {
    "group": "com.wdiscute",
    "module": "wdUtils",
    "version": "1.3-NEOFORGE-1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "wdUtils-1.3-NEOFORGE-1.21.1.jar",
          "url": "wdUtils-1.3-NEOFORGE-1.21.1.jar",
          "size": 36986,
          "sha512": "1da7b35b1956a90298ae5bc47e376dedf72d6ad7914ecb113545f5af146422ddfe1dcd98a7b2f3865a116e1568d37e7995d448f91aeca2ba1b12ad7d86049937",
          "sha256": "2ecbb46e170b921ad691f96d9fe3c25cac47d83ded4d5a6a63a598c3ffc7afd8",
          "sha1": "e8cd01f19ce8b591224fea3cb357bd99521a622e",
          "md5": "70953cd3dbf6cc868a4aaf2fbe923de9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.emi",
          "module": "emi-neoforge",
          "version": {
            "requires": "1.1.22+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "wdUtils-1.3-NEOFORGE-1.21.1.jar",
          "url": "wdUtils-1.3-NEOFORGE-1.21.1.jar",
          "size": 36986,
          "sha512": "1da7b35b1956a90298ae5bc47e376dedf72d6ad7914ecb113545f5af146422ddfe1dcd98a7b2f3865a116e1568d37e7995d448f91aeca2ba1b12ad7d86049937",
          "sha256": "2ecbb46e170b921ad691f96d9fe3c25cac47d83ded4d5a6a63a598c3ffc7afd8",
          "sha1": "e8cd01f19ce8b591224fea3cb357bd99521a622e",
          "md5": "70953cd3dbf6cc868a4aaf2fbe923de9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "wdUtils-1.3-NEOFORGE-1.21.1-sources.jar",
          "url": "wdUtils-1.3-NEOFORGE-1.21.1-sources.jar",
          "size": 12161,
          "sha512": "f104611f577b9346a348db445ee37d7b173bf950fbad9b88f8a50baa14407b1c9a3fdd593e0f2b30c3ca38617dcdc93275531a24442286b5b08fe510a226071b",
          "sha256": "f1c2f35d6eb6b68d2df8f3684c60c0d6fc6f475493b480086cf61e04c1e08e2c",
          "sha1": "43e87e8b2256b27dbf26b91939ad093170123c5c",
          "md5": "14f32d145cccf831e6cdf81cf8153631"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "wdUtils-1.3-NEOFORGE-1.21.1-javadoc.jar",
          "url": "wdUtils-1.3-NEOFORGE-1.21.1-javadoc.jar",
          "size": 182008,
          "sha512": "b7187979ba7113e9258c6f6ef6f61c9395011d418e01d52fe93e1d8a64298c4312078d1013b0a4c99950d9b9a5a718b6c06b9d35e9eec0c6d24884e874799340",
          "sha256": "51dc9cc0709b62436507662c6530dbd0ea02e0322e82f944c6588b1ab5f7c5fc",
          "sha1": "a66344e5ff637490b4b575c55cd1cdcc1d88acb8",
          "md5": "2ea95f818ff3f3a5c3885a3d3833edf0"
        }
      ]
    }
  ]
}
